### ISSUE TITLE
Can `request` dependency be replaced?

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/passport-oxd#3]
About [this](https://github.com/GluuFederation/passport-oxd/blob/master/package.json#L37) dep

It turns out `request` was deprecated. See:
- https://github.com/request/request#deprecated
- https://github.com/request/request/issues/3142
- https://github.com/request/request/issues/3143 

Hopefully we can use a different lib for our purposes

**Comment by ldeveloperl1985** [comment]
Done. Also updated on the npm repo https://www.npmjs.com/package/passport-oxd
